name = "Astolofo Modpack"
author = "imahotdog, thePlaceholder"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51323ee96318af9ac0e59f8108d154c933e6088e0c6681f59187de1cf9935243"

[versions]
forge = "40.2.11"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18"]
