name = "Astolofo Modpack"
author = "imahotdog, thePlaceholder"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "702bb89514a0539bc15e249a87628f667eb34e74082763cd0d3fa98774990f09"

[versions]
forge = "40.2.11"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18"]
